---
- name: Install Postgres Server
  hosts: erebor
  tasks:
   - name: Install postgres
     block:   
       # To get 9.5 version of postgresql
       - name: create file for postgres repo
         file: path="/etc/apt/sources.list.d/postgresql.list" state=touch
         changed_when: False

       - name: add postgres repo to file
         lineinfile: line="deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main 9.5" dest="/etc/apt/sources.list.d/postgresql.list" state=present

       - name: Get apt-key for psql version 9.5
         apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

       - apt: update_cache=yes

       - apt: name={{item}} update_cache=true state=latest
         with_items:
           - bash
           - openssl
           - libssl-dev
           - libssl-doc
 
           - postgresql-client-9.5
           - postgresql-common
           - postgresql-9.5
           - vim
           - python
           - python-dev
           - libpq-dev
           - gcc
           - npm
           - python-setuptools
           - python-pip
           - python-psycopg2

       - apt: upgrade=dist


   - name: Initiate and start database
     block:
       - command: service postgresql initdb
                creates=/var/lib/pgsql/data/postgresql.conf
       
       - name: Start PostgreSQL and enable at boot
         service: name=postgresql
                  enabled=yes
                  state=started
  
       - name: Ensure PostgreSQL is listening on all localhost
         lineinfile: dest=/var/lib/pgsql/data/postgresql.conf
                     regexp='^#?listen_addresses\s*='
                     line="listen_addresses = '127.0.0.1'"
                     state=present
         notify: restart postgresql

       - lineinfile: dest=/var/lib/pgsql/data/pg_hba.conf
                     regexp='host\s+all\s+all\s+127.0.0.1/32\s+md5'
                     line='host all all 127.0.0.1/32 md5'
                     insertbefore=BOF
         notify: restart postgresql

  handlers:
   - name: restart postgresql
     service: name=postgresql state=restarted