- name: check if copy (below) has already been performed pg_hba
  stat: path=/etc/postgresql/9.5/main/pg_hba.conf.bak
  register: pg_hba_check
  changed_when: False

- name: rename default config files
  command: cp /etc/postgresql/9.5/main/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf.bak
  when: pg_hba_check.stat.exists == False

- name: check if copy (below) has already been performed for postgresql
  stat: path=/etc/postgresql/9.5/main/postgresql.conf.bak
  register: postgresql_check
  changed_when: False

- name: rename default config files 
  command: cp /etc/postgresql/9.5/main/postgresql.conf /etc/postgresql/9.5/main/postgresql.conf.bak
  when: postgresql_check.stat.exists == False

- name: delete default config files
  file: path=/etc/postgresql/9.5/main/{{item}} state=absent
  with_items:
    - pg_hba.conf
    - postgresql.conf

- name: copy over configs for postgres
  copy: src={{item}} dest=/etc/postgresql/9.5/main/{{item}}
  with_items: 
    - pg_hba.conf
    - postgresql.conf
- service: name=postgresql state=restarted
